{% set name = "pylhe" %}
{% set version = "1.0.4" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pylhe-{{ version }}.tar.gz
  sha256: b0a2e00a99d3e50ec23af1c2243d1afdb615a19766c4bb84a39575a27581a118

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling >=1.13.0
    - hatch-vcs >=0.3.0
  run:
    - awkward >=2.7
    - python-graphviz >=0.19
    - particle >=0.25
    - python >={{ python_min }}
    - vector >=1.5.2

test:
  imports:
    - pylhe
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/scikit-hep/pylhe
  summary: A small package to get structured data out of Les Houches Event files
  dev_url: https://github.com/scikit-hep/pylhe
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - APN-Pucky
    - matthewfeickert
    - eduardo-rodrigues
    - lukasheinrich
    - conda-forge/scikit-hep
